# Generated by Django 5.0.3 on 2024-04-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_worn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoelace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoelacetype', models.CharField(choices=[('Nylon', 'Nylon'), ('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Raw Hide', 'Raw Hide')], default='Nylon', max_length=10)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
